PROJECTS = {
    "kayhomes": {
        "title": "KayHomes",
        "category": "Modern Real Estate Platform",
        "image": "images/ph1.png",
        "description": "A real estate platform that simplifies property discovery, listing management, and communication between buyers and property owners.",
        "overview": "KayHomes brings property search, owner tools, and buyer communication into one responsive application designed for the Nigerian property market.",
        "features": ["Property listings", "Cloudinary image uploads", "Authentication", "Favorites", "Search and categories", "Owner dashboard", "Property details", "Responsive design"],
        "technologies": ["Flask", "Python", "MySQL", "Bootstrap", "SQLAlchemy", "Cloudinary", "Railway", "Jinja2"],
        "challenge": "Property media, discovery filters, and owner workflows needed to remain fast and understandable on both phones and desktops.",
        "solution": "The application uses structured listing data, cloud-hosted media, focused search controls, and role-aware dashboard flows in a responsive Bootstrap interface.",
        "live_url": "https://kayhomes-production-07f2.up.railway.app/",
        "github_url": "https://github.com/popoolaisaiah2003-lgtm/kayHomes.git",
        "status": "Completed",
    },
    "knotique": {
        "title": "Knotique Crochet",
        "category": "Luxury Crochet E-commerce",
        "image": "images/ph2.png",
        "description": "A luxury crochet e-commerce platform for browsing handcrafted products, managing wishlists, placing orders, and shopping securely.",
        "overview": "Knotique translates a handcrafted fashion brand into an elegant digital storefront with practical customer and catalogue workflows.",
        "features": ["Product catalogue", "Customer accounts", "Wishlists", "Order placement", "Product categories", "Responsive storefront"],
        "technologies": ["Python", "Flask", "Bootstrap", "MySQL", "SQLAlchemy", "Jinja2"],
        "challenge": "The storefront needed to communicate a luxury identity while keeping product discovery and ordering straightforward on small screens.",
        "solution": "A focused catalogue hierarchy, reusable Flask templates, and mobile-first product layouts keep the experience polished and easy to navigate.",
        "live_url": None,
        "github_url": "https://github.com/popoolaisaiah2003-lgtm/-KnotiQue.git",
        "status": "Completed",
    },
    "yan-zhen-peptides": {
        "title": "Yan Zhen Peptides Website",
        "category": "Business Website",
        "image": "images/main.png",
        "description": "A modern business website for a peptide supplier with clean product presentation, contact integration, and responsive UI.",
        "overview": "The Yan Zhen Peptides website presents supplier information and products through a clear, responsive business interface.",
        "features": ["Responsive design", "Product display", "Contact integration", "Modern UI"],
        "technologies": ["HTML5", "CSS3", "Bootstrap", "JavaScript"],
        "challenge": "Technical product information had to remain readable and credible across a broad range of screen sizes.",
        "solution": "A restrained visual hierarchy and responsive product presentation make key information easy to scan without compromising the business identity.",
        "live_url": None,
        "github_url": None,
        "status": "Completed",
    },
}