PROJECTS = {
    "kayhomes": {
        "title": "KayHomes",
        "category": "Modern Real Estate Platform",
        "subtitle": "Property discovery and owner workflows for the Nigerian market",
        "image": "images/ph1.png",
        "description": "A real estate platform that simplifies property discovery, listing management, and communication between buyers and property owners.",
        "overview": "KayHomes brings property search, owner tools, and buyer communication into one responsive application designed for the Nigerian property market.",
        "features": ["Property listings", "Cloudinary image uploads", "Authentication", "Favorites", "Search and categories", "Owner dashboard", "Property details", "Responsive design"],
        "technologies": ["Flask", "Python", "MySQL", "Bootstrap", "SQLAlchemy", "Cloudinary", "Railway", "Jinja2"],
        "challenge": "Property media, discovery filters, and owner workflows needed to remain fast and understandable on both phones and desktops.",
        "solution": "The application uses structured listing data, cloud-hosted media, focused search controls, and role-aware dashboard flows in a responsive Bootstrap interface.",
        "live_url": "https://kayhomes.kaydevs.com/",
        "github_url": "https://github.com/popoolaisaiah2003-lgtm/peptide.git",
        "status": "Completed",
    },
    "knotique": {
        "title": "Knotique Crochet",
        "category": "Luxury Crochet E-commerce",
        "subtitle": "Elegant storefront for handcrafted fashion and checkout flows",
        "image": "images/ph2.png",
        "description": "A luxury crochet e-commerce platform for browsing handcrafted products, managing wishlists, placing orders, and shopping securely.",
        "overview": "Knotique translates a handcrafted fashion brand into an elegant digital storefront with practical customer and catalogue workflows.",
        "features": ["Product catalogue", "Customer accounts", "Wishlists", "Order placement", "Product categories", "Responsive storefront"],
        "technologies": ["Python", "Flask", "Bootstrap", "MySQL", "SQLAlchemy", "Jinja2"],
        "challenge": "The storefront needed to communicate a luxury identity while keeping product discovery and ordering straightforward on small screens.",
        "solution": "A focused catalogue hierarchy, reusable Flask templates, and mobile-first product layouts keep the experience polished and easy to navigate.",
        "live_url": None,
        "github_url": "https://github.com/popoolaisaiah2003-lgtm/-KnotiQue.git",
        "status": "Almost completed",
    },
    "yan-zhen-peptides": {
        "title": "Yan Zhen Peptide",
        "category": "Production-ready Flask Platform",
        "subtitle": "Production-ready Flask platform for a Chinese peptide company",
        "image": "images/yan-zhen-peptide.png",
        "description": "Built a full-stack Flask web application for a Chinese peptide company featuring a product catalog, COA reference system, customer inquiry management, order-status workflow, and a responsive admin dashboard. The platform includes secure form handling, database migrations, notification badges, and Railway deployment.",
        "overview": "Yan Zhen Peptide is a production-focused Flask platform that combines catalogue browsing, COA references, customer inquiry handling, and order status workflows in one cohesive system.",
        "features": ["Product catalog", "COA reference system", "Customer inquiry management", "Order-status workflow", "Responsive admin dashboard", "Secure form handling", "Database migrations", "Notification badges"],
        "technologies": ["Flask", "Python", "SQLAlchemy", "MySQL", "Bootstrap", "JavaScript", "Railway"],
        "challenge": "The platform needed to unify research-product content, compliance references, and internal status operations without sacrificing speed or clarity for staff and customers.",
        "solution": "A modular Flask architecture with SQLAlchemy-backed workflows, migration-safe schema evolution, and responsive Bootstrap interfaces delivered reliable operations from catalog to inquiry and fulfillment updates.",
        "live_url": "https://peptide-production-21ed.up.railway.app",
        "github_url": "https://github.com/popoolaisaiah2003-lgtm/peptide.git",
        "status": "Completed",
    },
}